# This is a basic workflow to help you get started with Actions

name: CI

# this will happen once a week
on:
  schedule:
    - cron: 0 0 * * 6
  push:
    paths:
      - '.github/workflows/update.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
   # updates niv and javascript dependencies
    - name: Update niv dependencies
      run:  GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} nix run nixpkgs.niv -c niv update
      
    - name: Update JavaScript packages
      run: |
        nix-env -iA nix-gen-node-tools -f pkgs/default.nix
        cd pkgs
        mv js old-js
        mkdir js
        mv old-js/default.nix js/
        for i in $(ls old-js/); do
          (cd js/ && nix-gen-node-tools $i)
        done
        rm -rf old-js/
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Updated package dependencies
        branch: update
        branch-suffix: timestamp
        
