# This is a basic workflow to help you get started with Actions

name: CI

# this will happen once a week
on:
  schedule:
    - cron: 0 0 * * 6

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-ustable
    # updates niv and javascript dependencies
    - name: Update dependencies
      run: |
        nix run nixpkgs.niv -c niv update
        nix-env -iA nix-gen-node-tools -f pkgs/default.nix
        cd pkgs
        mv js old-js
        mkdir js
        mv old-js/default.nix js/
        for i in $(ls old-js/); do
          (cd js/ && nix-gen-node-tools $i)
        done
        rm -rf old-js/
        
    - name: Create PR
      uses: funivan/github-autopr@0.2.0
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
